### ISSUE TITLE
Don't remove ESLint?

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-tslint#1]
Our project, like many TypeScript projects, is in a slow process of transition. We want to be linting both our unconverted JavaScript and our converted and new TypeScript.

In our specific case, we also have separate eslint and tslint configs, so we want both to run!

**Comment by t-sauer** [comment]
I think for already existing projects it makes sense to keep the ESLint config around, I agree with that.
On the other side though, I think it can be annoying to remove ESLint by hand when you install it in a new app and you basically start with TypeScript right from the beginning. So I guess the question is which one is more common.

**Comment by simonihmig** [comment]
> So I guess the question is which one is more common.

Let the user decide by showing a prompt?
