### ISSUE TITLE
Safe-by-default: underscore-prefixed unused args

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-tslint#14]
Currently if you create a new ember app, add `ember-cli-typescript` and `ember-cli-tslint`, followed by something like

`ember g route home`

and then define a route as shown below, you'll get two warnings from the TypeScript compiler due to [`ember-cli-typescript` using the `--noUnusedParameters` flag](https://github.com/typed-ember/ember-cli-typescript/blob/1dfb15698d0db87e4398560301b41d9bc3cb2fdc/blueprints/ember-cli-typescript/files/tsconfig.json#L14)

```ts
import Route from "@ember/routing/route";
import { Ember } from "ember";
import Model from "ember-data/model";

export default class Home extends Route.extend({
  // anything which *must* be merged to prototype here
}) {
  // normal class body definition here
  public async afterModel(
    resolvedModel: Model,            // WARNING: 'resolvedModel' is declared but its value is never read.
    transition: Ember.Transition     // WARNING: 'transition' is declared but its value is never read.
   ) {}
}
```
[The TS team has adopted leading underscores as way of treating unused variables without losing developer intent](https://github.com/Microsoft/TypeScript/pull/9464) (i.e., naming a parameter `_` doesn't leave info for fellow developers who may want to use it in the future -- `_model` gives them a clue).

Unfortunately, in an ember app, this leads to a tslint error. Apparently Palantir feels that unused parameters of any kind should be treated as errors.

https://github.com/palantir/tslint/blob/9d7db479596c50bbf89fa87d498ab927763a6eec/src/configs/recommended.ts#L187-L192

```ts
import Route from "@ember/routing/route";
import { Ember } from "ember";
import Model from "ember-data/model";

export default class Home extends Route.extend({
  // anything which *must* be merged to prototype here
}) {
  // normal class body definition here
  public async afterModel(
    _resolvedModel: Model,            // ERROR: [tslint] variable name must be in lowerCamelCase, PascalCase or UPPER_CASE (variable-name)
    _transition: Ember.Transition     // ERROR: [tslint] variable name must be in lowerCamelCase, PascalCase or UPPER_CASE (variable-name)
   ) {}
}
```

This leaves developers with guaranteed errors or warnings by default, the first time they run into a situation where they must disregard a function parameter.

Let's adopt Microsoft's convention and allow these leading underscores by default across all ember apps. We'd need to allow this by default for JS and TS.

```json
    "variable-name": {
      "options": ["allow-leading-underscore"]
    }
```

**Comment by t-sauer** [comment]
I think the recommended preset is a bad collection of rules in general (way too many stylistic opinions for example) . It might be worth revisiting the standard config in general and see if there is a better preset or a custom set of rules we could use.

**Comment by mike-north** [comment]
@t-sauer what are your thoughts on making this change now, and opening a new RFC-style issue for discussing an even better baseline?

In terms of a developer's hierarchy of needs, "It doesn't error under normal circumstances" outranks "this configuration is delightful".

Ideally, I'd love to leverage [some of the work my LinkedIn colleagues and others have done](https://github.com/ember-best-practices/eslint-plugin-ember-best-practices) with ember-specific TS rules.

**Comment by mike-north** [comment]
I'd be happy to make this change, if you give me the 👍

**Comment by t-sauer** [comment]
Sure, I am happy for suggestions 🙂
