### ISSUE TITLE
Switch the dependency of broccoli-tslinter?

### ISSUE THREAD

**Issue by guangda-prosperworks** [typed-ember/ember-cli-tslint#4]
Hey just let you know I've submitted another issue here: https://github.com/kratiahuja/broccoli-tslinter/issues/25
But do you have any plan to switch the dependency of broccoli-tslinter? Or is possible to contact that author. It's not being updated for 5 months.

**Comment by t-sauer** [comment]
It was recently updated so I think it is totally fine to stick with it.
