### ISSUE TITLE
State broken "rule" with linting failures

### ISSUE THREAD

**Issue by mike-north** [typed-ember/ember-cli-tslint#7]
Currently, rule violations do not state the name of the rule in question being violated. 

<img width="667" alt="screen shot 2017-12-16 at 11 25 26 am" src="https://user-images.githubusercontent.com/558005/34072828-de2e6bcc-e253-11e7-9259-0cc8c9ddc305.png">

**User Story:**
> As a developer, I need to be able to know the name of the rule being violated in order to decide whether I want to disable the rule or alter my code to align with it.

**Comment by t-sauer** [comment]
Good catch. I totally agree.  
I have created a PR over at `broccoli-tslinter` to resolve the problem: https://github.com/kratiahuja/broccoli-tslinter/pull/27
